### ISSUE TITLE
delta between sessions

### ISSUE THREAD

**Issue by boryeumao** [tasket/wyng-backup#111] opened 2022-08-27 20:13 UTC
For a few good-sized volumes, I'd like to be able to get changed/new files in a session relative to an older one, without "receiv'ing" the sessions first.  Maybe this has been covered in existing issues? otherwise is this possible (maybe a pointer to where to look)?  Thanks.

**Comment by tasket** [comment] 2022-08-27 23:07
@boryeumao Yes this would be a duplicate of issue #16 as there is no decent way to access a volume's filesystem other than mounting it, so creating a FUSE module to access Wyng archives would be the way to go.

**Closed by tasket** 2022-08-27 23:07 UTC

**Comment by boryeumao** [comment] 2022-08-28 02:54
Got it - thanks
