### ISSUE TITLE
Reuse send "partial session dir" instead of deleting it

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#85] opened 2021-07-21 14:34 UTC
As you know, sending over network comes with more delays and connection issues sometimes. SSHFS is more capricious, and having to resend changes, for example a Windows10 upgrade, can result easily into 8GB of changes in a send session.

If wyng was able to reuse previously incomplete send session instead of deleting it, it would be more resilient under ssh, qubes-ssh and qubes over sshfs modes.

**Comment by tasket** [comment] 2021-07-21 15:28
Yes. But this is a duplicate of issue #15.

**Closed by tasket** 2021-07-21 15:28 UTC
