### ISSUE TITLE
Wyng in crontab doesn't execute send

### ISSUE THREAD

**Issue by igor-rossetti** [tasket/wyng-backup#103] opened 2022-07-06 11:58 UTC
Hello.

This is my crontab `/etc/cron.d/wyng-send`

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

* 3 * * * root su -l -c '/usr/local/bin/wyng send vm-108-disk-0 > /tmp/log.txt 2>&1'
```

and this is /tmp/log.txt

```
Destination not ready to receive commands.
Wyng 0.3.0rc2 20210622
```

The same command works in terminal.

**Comment by tasket** [comment] 2022-08-04 20:32
@igor-rossetti I'm not able to reproduce the problem on Ubuntu 22.04 using the current Wyng v0.3.1.  Could you try with the updated version?

**Comment by tasket** [comment] 2022-08-27 23:47
Closing this for now, with one further suggestion to use the `-u` option (unattended or non-interactive) whenever calling Wyng from an automated script or daemon.

**Closed by tasket** 2022-08-27 23:47 UTC
