### ISSUE TITLE
terminated untar process!

### ISSUE THREAD

**Issue by gangamstyle** [tasket/wyng-backup#43] opened 2019-10-01 22:09 UTC
sparsebak.py send
100% 500Mb
terminated untar process!

Is this okay?

**Comment by tasket** [comment] 2019-10-02 11:48
It isn't supposed to do that normally. Does it happen repeatedly? And can you provide more details?

If you're concerned whether the backup completed properly, you can run 'verify' on it.

**Comment by gangamstyle** [comment] 2019-10-02 23:32
yes it happen repeatedly
details:
~5Gb volume, not first backup, slow network storage
increasing pause to 15s doesn't help

**Comment by tasket** [comment] 2019-10-03 13:59
What dest mode are you using... internal, ssh, qubes or qubes-ssh? If not internal, what OS is the dest running?

One more thing you can try is on the line `for i in range(30):` change 30 to 60.

Also, if there is no error, the backups are probably completing OK. This is because the last files received by tar are then accessed one last time; if the files didn't get saved an error would occur and the program would stop. However, you can check this manually by looking at the "volinfo" file both in the /var/lib/sparsebak/default/volumename path and also in the backup path. The two files should contain exactly the same data.

**Comment by gangamstyle** [comment] 2019-10-03 21:07
tested backup:
sparsebak.py verify volume
100%
Ok

Steps to remove last backup session to repeat it with modified sparsebak.py ?

**Comment by tasket** [comment] 2019-10-04 19:24
There is no easy way to remove the last backup. You could modify the volume in some small way (create a file and delete it) to get it to backup again.

**Comment by tasket** [comment] 2020-08-25 18:24
Haven't reproduced this, so I'm closing for now.

**Closed by tasket** 2020-08-25 18:24 UTC
