### ISSUE TITLE
Upgrade from old backup: "Not a Wyng format"

### ISSUE THREAD

**Issue by gangamstyle** [tasket/wyng-backup#169] opened 2023-07-26 18:04 UTC
Upgrading backup from 0.3.0rc2 to the latest wyng. This error happens:
line 4442, "Not a Wyng format."

New wyng expects [WYNG%d2] prefix, but archive.ini starts with [var]...
Any manual to upgrade from the old version ?
Should I use some other intermediate wyng versions to update backups automatically?

**Comment by tasket** [comment] 2023-07-28 13:54
@gangamstyle This is a duplicate of #113.  Its still an open issue and hasn't been implemented yet.  There is no older/intermediate version that will convert from v0.3.

**Closed by tasket** 2023-07-28 13:54 UTC
Labels: duplicate
